version: "3.3"
services:
    rest-database:
        image: postgres:latest
        ports:
            - 5433:5432
        hostname: rest-database
        env_file:
            - .env
        volumes:
            - postgresql:/var/lib/postgresql/data
        networks:
            - rest-backend
    rest-app:
        build: 
            context: ./
        ports:
            - 8003:8003
        hostname: rest-app
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - rest-database
        networks:
            - rest-backend

networks:
    rest-backend:
        driver: bridge

volumes:
    postgresql:
        driver: local
