version: "3.3"
services:
    rest-database:
        image: postgres:latest
        ports:
            - 5433:5432
        hostname: rest-database
        env_file:
            - .env
        volumes:
            - ./postgresql:/var/lib/postgresql/data
#     rest-app:
#         image: if3110-rest-app-1:latest
#         ports:
#             - 8003:8003
#         hostname: rest-app
#         env_file:
#             - .env
#         volumes:
#             - .:/app
#             - /app/node_modules
#         depends_on:
#             - rest-database

# networks:
#     rest-database-rest-app:
#         driver: bridge
